LUBA-12: Add base react routing
kirillsud/luba-web pull request #2
Opened 2023-07-03 21:01 UTC by verymarin

2023-07-03 21:28 UTC, kirillsud requested changes

2023-07-03 21:28 UTC, kirillsud commented on src/app/components/main-menu/main-menu.tsx
> +          <Link to="/">MainMenu root</Link>
Can we add one more link to test the route to projects?

2023-07-04 20:04 UTC, kirillsud approved these changes, later dismissed

2023-07-04 20:07 UTC, verymarin commented on src/app/components/main-menu/main-menu.tsx
> +          <Link to="/">MainMenu root</Link>
<img width="348" alt="image" src="https://github.com/kirillsud/luba-web/assets/138394424/67a59162-e372-4740-8c82-a856b5056e54">

<img width="363" alt="image" src="https://github.com/kirillsud/luba-web/assets/138394424/d21f601e-cb5a-456a-99d1-8e2b26f252e0">


done

2023-07-04 20:22 UTC, pavelatr111 approved these changes

2023-07-04 20:24 UTC, kirillsud approved these changes

2023-07-04 20:37 UTC, merged