added gallery to portfolio page
kirillsud/luba-web pull request #3
Opened 2023-07-05 22:36 UTC by pavelatr111

2023-07-19 16:23 UTC, kirillsud requested changes
Хорошая работа. Нравится решение для рендера трёх колонок. Думаю, это самый правильный вариант.

Из того, что не понравилось - это отсутствие коммуникации с твоей стороны когда столкнулся с проблемой отступа бокового меню. Судя по количеству разных применённых стилей и комментариям - кажется что ты потратил много времени на поиск решения. Если бы написал в чат команды - думаю мы смогли бы вместе найти верное решение гораздо быстрее. Ну или как минимум смогли бы объяснить причины по которым `MainMenu` было так сделано.

Закрываю ревью со статусом **Request changes** потому нужны некоторые правки.

2023-07-19 16:23 UTC, kirillsud commented on src/app/components/layout/layout.module.css
> +  /* padding: 1rem; */
Зачем убрал?

2023-07-19 16:23 UTC, kirillsud commented on src/app/components/main-menu/main-menu.tsx
> +      {/* <div className={styles['placeholder']}></div> */}
Я понимаю какую проблему ты пытался тут решить. Но то решение которые ты предлагаешь создаёт зависимость (неявную связь) между компонентами: всем страницам нужно знать что `MainMenu` имеет ширину 200px и они должны адаптировать свои стили учитывая это.

Изначальная задумка была в том, чтобы такой зависимости не было. Меню занимает свои N пикселей от ширины экрана а всё остальное используется под страницы сайта. Посколько меню имеет `position: fixed;` то пришлось добавить блок `placeholder` который создаст сдвиг остальных блоков (`page`) на ширину меню.

И это было сделано с ошибкой. Чтобы исправить нужно добавить для класса `.placeholder` стиль
`min-width: 200px;`. Тогда все костыли касательно стилей отступов в `portfolio-page.module.css`  можно убрать.

2023-07-19 16:23 UTC, kirillsud commented on src/app/pages/portfolio-page/portfolio-page.module.css
> +    display: block; */
Если эти комменты очень важно оставить то добавь коммент выше с пояснением зачем они. Если нет - удаляй. Не следует добавлять в код никому не нужные комменты.

2023-07-19 16:23 UTC, kirillsud commented on src/app/components/main-menu/main-menu.module.css
> +  z-index: 0;
Какую проблему это решает?

2023-07-19 16:23 UTC, kirillsud commented on src/app/pages/portfolio-page/portfolio-page.tsx
> +    portfolio: { img: string; id: number }[];
Реализация не соответствует с требованиями:
1. поле должно называться `projects` а не `portfolio`
2. не соответствуют названия полей в объекте
3. не хватает поля `name`

2023-07-19 16:23 UTC, kirillsud commented on src/app/pages/portfolio-page/portfolio-page.tsx
> +            <div>
Для чего этот `div`?

2023-07-19 16:23 UTC, kirillsud commented on src/main.tsx
> +        element: <ProjectPage galleryImages={galleryImages} />,
Нужно откатить все изменения по ProjectPage. Это будет сделано в рамках другой задачи

2023-07-19 16:23 UTC, kirillsud commented on src/assets/constants.ts
> +export const galleryImages: { img: string; id: number }[] = [
Смущает название. По смыслу это должен быть список проектов.
```suggestion
export const projects: { img: string; id: number }[] = [
```

2023-07-19 16:23 UTC, kirillsud commented on src/main.tsx
> +import { galleryImages } from './assets/constants';
Вся JavaScript реализация должна быть в папке `./app`. В `assets` должен лежать только медиа контент который потом уйдёт клиенту как есть. Например картинки или шрифты.

2023-07-31 13:15 UTC, verymarin commented on src/app/components/main-menu/main-menu.tsx
> +      {/* <div className={styles['placeholder']}></div> */}
как будто уже решена проблема

2023-07-31 13:16 UTC, verymarin commented on src/app/pages/portfolio-page/portfolio-page.module.css
> +    display: block; */
удалю

2023-07-31 13:18 UTC, verymarin commented on src/main.tsx
> +import { galleryImages } from './assets/constants';
реализовала в папке ./app/utils

2023-08-10 22:30 UTC, merged